---
title: "A list of Twitter bios"
author: "David Rickmann"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

There are two approaches to the Twitter bio space. 
You could write a sensible description of yourself that people might find helpful or informative, or you can just put a bunch of nonsense that you think sounds nice.
I prefer the second option.

I also like to change them fairly often so here is a list of some Twitter Bios from most recent to least recent.


## 30th September 2019

### "It's me Nono, small robot you know! Friend of Ulysses"

This is a line from the theme tune to the 1980's French/Japanese animated show Ulysses 31.
It's a really weird line, because no one else gets introduced in the credits (except Ulysses himself and I suppose very briefly Telemachus, his son.)
Also it doesn't really fit into the song at all.



## 20th September 2019

### "More a Mermaid than a Ghost, More a Castle than a Manor"

I was trying to describe the Nereid to players in the Hidden Shrine of Tamochoan. I called her a water spirit, but I didn't want the players to think she was insubstantial (or was an actual mermaid). They found the phrasing funny,
A week later in a different game the DM described a run down mansion as "More a Castle than a Manor". The players found the juxtaposition funny and I thought it sounded a bit poetic. So there we go.


