# Daily Writing Exercise Topics 


## Productivity tools

RescueTime

analysing todoist data



## Elephants. I guess.

More on topsy
Murderous Mary

## Checking
 
 Checking is important.

Why checking is important

checking your results


checking as you go
In data science you will often be taking a set of inputs and transforming them






## Why autonomous cars are not a solution.

The problem with cars is not anything to do with humans having to drive them.


## River freight and local hubs.

Most towns in Britain are built around a river. Not all, but most.
This is because rivers provide several vital functions. 

Firstly, how do you get fresh water.
Secondly, how do you get rid of sewage.
Rivers are great at both of these, for a while. But as the numbers go up, so do the problems.

Rivers are also pretty great for moving stuff around.
But we don't do that anymore. Why now?




## Last mile for humans and for freight.
drone hubs.
Link to river freight.

## Epistemic groups within transport or engineering

## Building self presenting models with R 

## Replacing powerpoint with R Shiny

## R Markdown experiments

embedding graphs and stuff in R markdown
```{r cool-plot, fig.cap='A cool plot.'}
plot(cars, pch = 20)  # not really cool
```


## Transport data formats
GTFS
TransXChange
CIF
Etc.

## Being an expert
I'm at an odd point with expertise. I'm clearly an expert at something. I have all the trappings. I tend to be employed as a senior something or a principal something else. I've been doing what is now called "Data Science" for at least 15 years. But I don't really feel like I know anything. Or at least, everything I do think I know is very obvious. Anyone could do it.
The problem is (I hope) to do with 
Everything I read is written by people who really do know what they're doing. Those are the people I want to learn things from. There are lots of them and they all know a lot of things that I do not know. Those are the intersting and useful skills, not the ones I've got.
For now I will try and comfort myself with the thought that it's my expertise that highlights 

## Creating a recipe Schema

*More on cooking*
Should we key the ingredients?
Does it make sense to have butter (for example) listed more than once.
Well, yes, if you use it for different things.
Quite often a cake will have butter but will also have butter cream frosting. If it's all listed together you need to specifiy in the recipe how much to use. I think it would be better to have a field listing sub assemblies of the recipe and keying on sub assembly+ingredient 
reference cooking for engineers


## Command Interface




## Training Neural Nets and Sniffer dogs


## A shared universe management system

Shared universes are great.
Giant entertainment conglomerates are not great

But giant shared universes do need some kind of regulating authority to suggest what is cannon and what is not cannon.
What if we could have a story universe system a bit like software repositories.

Each story could list it's requirements
(example, you're writing about peter parker spiderman, set and include at teh start of your story including peter parker origin)

Then these stories can be assembled into a coherent universe.
Don't like a story? Fork the universe. Built your own distribution which includes what you like and excludes what you don't.
Or, maybe you like a story that was set a long time before your universe, you want your characters to refer to it, but don't want it to have actually happened in universe import that story as a myth?




