---
title: Projects Diary
author: David Rickmann
date: '2020-07-30'
draft: FALSE
---


I'm going to try and keep a track of how various projects are going all in one place and push it at the end of the month. 
This means I can make a note of smaller progress that doesn't warrant a post of it's own.

## Interface
### 2nd July 2020

Another fairly radical overhaul.
I've set up an openhab server. Openhab has already done the hard work of setting up bindings to common household smart devices. I'm generally a fan of not reinventing the wheel. This also means there is a whole community of folks working on interesting ways to talk to house gadgets.
I'm assuming there isn't going to be an Openhab binding for rudder hydraulics or diesel engine controls. 
I want this system to be doing more than just smarthome gadget control (though that is very much the core use case) so I'm planning a hybrid system. The openhab server handling talking to all the gadgets and then the Interface on top.

Openhab as a REST API so I've rewritten all the controls to use that. It's pretty quick to add more.

I've ordered a wifi light switch from China which was quite cheap but will take months to arrive.
I've heard mixed reviews, but if it works I will get a couple more. The boat doesn't actually have main lights in the hold, only lamps. So I can build the automation in at source when I finally get round to installing them.

### 16th July 2020

The aforementioned fancy lightswitch arrived much earlier!
But I realise I had not taken into account the fact that I have a light switch and a separate dimmer switch wired about a metre apart for absurd reasons. It would make sense (but be a lot more work) to uninstall the second light switch and just have the one. Especially since the dimmer doesn't work all that well with LED bulbs, but that's a lot more work. I do have a light installed in my wardrobe, which I might use as a test.

## Bits and Pieces

I've ended up not working that much on this project this month. At least, the later part.   
I did a few bits and pieces, but nothing very significant.

### OpenHab
I've tweaked the OpenHab server a little here and there, and added all the devices I could find that I could add. 
The Smart TV can be controlled via OpenHab, I can change channels, volume and turn it off, but I can't turn it on.
I added a new network switch so that it's on a wired connection, but still no luck.
Beyond that I think I need to start including some sensors and specific switched devices. 

I also want to look into the database hooks to add data persistence.

### Voice Recognition
I've added a very basic voice recognition layer using [annyang](https://www.talater.com/annyang/), a javascript voice recognition library.
It's relatively basic, but it does work.
I haven't really done much more than play with it.

### Weather.
I've messed around with the Norwegian Weather API but I've found it to be a little unreliable.
I STILL haven't added any error handling to that code, so if it can't get to the API it just breaks everything.
I think OpenHab can provide weather data, so I may swap to using that.



## Boatwork


### A New(ish) Door
The Front cabin had a door but that was before the corridor had a floor.
So I removed the door to add the floor {{% marginnote %}} Also, I added more walls. They got in the way a bit too. {{% /marginnote %}} and have only now got round to cutting it down to make it fit again.
So, now there is a door. That's something.


### Enforced Plumbing
There was a minor plumbing disaster in the kitchen which was 100% down to my fairly sloppy original installation work.
I did it in a rush because we hadn't had a kitchen in the boat. Ever. And I was keen to get it in.
However in fixing a blockage I disloged some pipes and then discovered my pipe access hatch had become blocked by a new wall I built.
I plan to fix that today (or maybe tomorrow, because today is busy).
This will fix several problems (Dishwasher flooding, sink flooding, mild panic about how bad the plumbing is. Emergency Valve Access, and so on.)

  
## Paid Work

Had a nice chat with the people at D2 Consulting and I'm going to start work with them in September as their new Principal Data Specialist.

  
  

