---
title: "The Colours of Butterflies"
author: "David Rickmann"
date: "2020-06-01"
series:
tags:
  - "physics"
---

I was working on a more complicated post about timetable data formats, but I've parked it for now because the child needed to be taken out to the woods to play. As we were watching the clouds of billions of tiny flies lit up by the setting sun and pretending to be galaxies I asked what I should write about instead. They said "Butterflies".

So here is a short post about butterflies.

Do you know, if you got the bluest of blue butterflies and took off it's wings {{% marginnote %}} I assured the child that you shouldn't do this. They asked why? I said that the butterfly wouldn't like it. They said that it might not like being caught but we could always make new wings for it out of paper. We decided together that it seemed like a lot of work, and maybe we'd best just think about the butterfly wings instead of catching them. Also there weren't any nearby. {{% /marginnote %}} and ground them up into a fine paste that there would not be a single speck of blue to be seen. 
This is because butterfly wings aren't pigmented, but have *structural colour*. The wings of butterflies are made up tiny tiny structures that cause the light travelling through them to interact, cancelling out some freuqencies and enhancing others. 

In butterflies there are several different mechanisms for achieving this, including: {{% marginnote %}} Bear with me, these descriptions are going to be super vague, because I'm writing it on a picnic table without any internet {{% /marginnote %}}

* diffraction gratings
  + A diffraction grating is a surface with several slits in it which cause the light to spread out. The resulting wave fronts interfere with each other.
* photonic crystals and crystal fibres.
  + These are tiny repeating crystal structures that allow photons to move through them in a specific pattern (a bit like the way electrons move in a transistor). 
   + Crystal fibres are, more or less, strings made up of stacks of diffraction gratings which act like photonic crystals
* selective mirrors
  + These are tiny tiny bowl shapes holes that reflect specific wavelengths. One colour from the center and another from the edges. 
* probably others ones that I don't know about.

One interesting upshot of this is that if you pour chocolate into a mould with a diffraction grating in it, you can make pure chocolate that looks like a rainbow.

```{r, eval=TRUE, echo = FALSE}
blogdown::shortcode("youtube", "l3ZFZ_ApzGY")
```
