---
title: "Advertising"
author: "David Rickmann"
date: '2020-07-14'
---

My wife is running some workshops [on critical thinking](https://notebook.lisamcnulty.co.uk/page/sherlock/) and why Sherlock Holmes is actually bad at it.
I've taken this opportunity to explore different ways to market this course.

I wanted to know how different ways of getting people's attention might work. {{% marginnote %}} This blog isn't one of them. It's not really here for anyone to actually read.   {{% /marginnote %}} The first thing I needed was a landing page so that I could see clearly on the analytics if people were following my links. That's the page linked to above.

I had a voucher for google adwords, so I took out an ad linked to that page. 

Fortuitously at the some time someone on twitter tweeted this:

{{% tweet 1282708852362956808 %}}

I enjoyed this tweet and joined in with a less funny version of basically the same joke. {{% marginnote %}} I generated a stock meme, on the same theme and tweeted it. It's a bit "Reply-Guy" style behaviour, but hopefully not too terrible. I was aiming more to engage with the suggestion that everyone was going to start making memes on the same subject. Anyway... it's a fine line, replying to other people's better jokes on Twitter. {{% /marginnote %}}
This was more popular than I expected, so, as part of an experiment I popped a "Check out my soundcloud" style tweet, linked to that same landing page.

After a day or so I checked the analytics for one day.

* Paid search advert: 9 (cost per click approx £1.50) 
* Twitter referral: 26 (cost per click 0)

A clear win for the viral tweet.

The conclusions here are so far that active social media engagement seems to be way better than paid advertising, especially for a very very small operation. Even a completely unrelated tweet garnered massively more traffic value than the paid search. Additionally, the paid search seems *really* expensive. This might be because I set it up badly (I definitely don't know what I'm doing when it comes to marketing) but it seems that I'm paying on an on click basis. I definitely would not have wanted to pay so much money for the results if it weren't for the voucher I'm using. 

Anyway.... 
Check out my insta to see more great products I guess?

